# Generated by Django 4.1.5 on 2023-01-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskText', models.CharField(help_text='Описание задачи', max_length=200)),
            ],
        ),
    ]
