# Generated by Django 4.1.5 on 2023-01-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='created_time',
            field=models.DateTimeField(auto_now=True, help_text='Дата создения задачи'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='finish_time',
            field=models.DateTimeField(default=None, help_text='Дата завершения задачи'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='is_done',
            field=models.BooleanField(default=False, help_text='Пометка о выполнении'),
        ),
    ]
