# Generated by Django 4.1.5 on 2023-01-27 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0002_tasklist_created_time_tasklist_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата создения задачи'),
        ),
    ]
