# Generated by Django 4.1.5 on 2023-01-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdlist', '0004_alter_tasklist_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='created_time',
            field=models.DateTimeField(auto_now=True, help_text='Дата создения задачи'),
        ),
    ]
